#pragma once

#include "g_vector2.h"
#include "g_vector3.h"
#include "g_vector4.h"
#include "g_matrix4.h"
#include "g_matrix3.h"
#include "g_matrix3x4.h"
#include "g_matrix3x2.h"
#include "g_matrix4x3.h"
#include "g_quaternion.h"
#include "g_transform3_util.h"
#include "g_transform_quat.h"
#include "g_line3.h"
#include "g_plane.h"
#include "g_triangle3.h"
